general.live_config_reload = true
[colors.normal]
black = "#1d2021"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16386"
red = "#cc241d"
white = "#fbf1c7"
yellow = "#fabd2f"

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
[font.offset]
y = -3
[scrolling]
history = 10000
[window.padding]
x = 12
y = 12
